// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2hShz3eiLIq721RMCfeLBi4ihVtM3U4E',
    appId: '1:860435024556:web:a94fdae0452007d25c2d09',
    messagingSenderId: '860435024556',
    projectId: 'nasa-app-df0e9',
    authDomain: 'nasa-app-df0e9.firebaseapp.com',
    storageBucket: 'nasa-app-df0e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9yG78WmuBHOiEwgAzHwplR0y2hKAjDNM',
    appId: '1:860435024556:android:1f0a9f12a551d09b5c2d09',
    messagingSenderId: '860435024556',
    projectId: 'nasa-app-df0e9',
    storageBucket: 'nasa-app-df0e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH4egwpzZ8KjeAb2wNUCa5myejjeNFxuk',
    appId: '1:860435024556:ios:fe7ba98d6aa5c6625c2d09',
    messagingSenderId: '860435024556',
    projectId: 'nasa-app-df0e9',
    storageBucket: 'nasa-app-df0e9.appspot.com',
    iosBundleId: 'com.hacks.nasaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH4egwpzZ8KjeAb2wNUCa5myejjeNFxuk',
    appId: '1:860435024556:ios:f18a0b7d2511c8755c2d09',
    messagingSenderId: '860435024556',
    projectId: 'nasa-app-df0e9',
    storageBucket: 'nasa-app-df0e9.appspot.com',
    iosBundleId: 'com.example.nasaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2hShz3eiLIq721RMCfeLBi4ihVtM3U4E',
    appId: '1:860435024556:web:2a1361f35424d9c35c2d09',
    messagingSenderId: '860435024556',
    projectId: 'nasa-app-df0e9',
    authDomain: 'nasa-app-df0e9.firebaseapp.com',
    storageBucket: 'nasa-app-df0e9.appspot.com',
  );
}
